name: Market Bot

on:
  schedule:
    # 🇮🇳 India Report (8:45 AM IST)
    - cron: "15 3 * * *"

    # 🌙 US Report (6:45 PM IST)
    - cron: "15 13 * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas requests pytz feedparser

      - name: Print Time (Debug)
        run: |
          echo "UTC Time:"
          date -u
          echo "IST Time:"
          TZ="Asia/Kolkata" date

      - name: Run bot
        run: |
          echo "Running bot..."
          python bot.py
          echo "Done."
