name: Market Bot

on:
  schedule:
    # 🇮🇳 India Report (8:40 AM IST)
    - cron: "10 3 * * *"

    # 🌙 US Report (7:00 PM IST)
    - cron: "30 13 * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas requests pytz feedparser

      - name: Run bot
        run: |
          echo "Starting bot execution..."
          python bot.py
          echo "Bot execution completed."
